services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: banking_db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      spring.datasource.url: jdbc:mysql://mysql:3306/banking_db
      spring.data.redis.host: redis
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started